### ISSUE TITLE
The newest version will appear some tmp file when edit files.

### ISSUE THREAD

**Issue by armink** [edubkendo/atom-racer#31]
![image](https://cloud.githubusercontent.com/assets/1734686/8130488/599fd60c-1145-11e5-892b-9a17ed914266.png)

I think it is not a good user experience. Blink files will move our attention. But the old version don't has this problem.

**Comment by alkama** [comment]
Hello,

Note: We now put the required temporary files in the project directory to help racer spot the projects "Cargo.toml" file so that it can help you complete even with your dependencies.
(We soon will even put those temp files in the same directory where your current edited file is).
That's to explain why we changed and dont put those files in the system temp folder.

Now about your problem:
Firstly, it's strange you have multiple temp files, they should disappear once the call to racer is completed.

Secondly, we shaped them as "._XXXXX" because the "._*" is ignored by default by Atom.
Check your Atom Settings:
* Open `Settings > Packages`
* Search the core package called `tree-view`, click `Settings`
* Check the box called `Hide Ignored Names`

You can control what is ignored in the main Atom settings top panel.

That, at least, should remove the flickers due to those temp files being hastily created and destroyed as racer is called.

**Comment by armink** [comment]
Thx. It isn't appear temp file When I check the box called `Hide Ignored Names`. :smile:
I think should write this tips to readme file. Perhaps you can add this check box to atom-racer.

**Comment by alkama** [comment]
I'll certainly add that to the readme soon.
And about adding a settings to toggle ignore on tree-view, I'm kinda reluctant to change a settings owned by another package.
Glad it fixed your problem anyway :)

**Comment by Fedcomp** [comment]
Any chance you will allow to set tmp directory via configuration? or even avoid tmp files in the future? sounds like it's pointless hdd/ssd rewrite operations

**Comment by melroy89** [comment]
You could.. also store this temp files in some user ~/.blbla hidden directory. So the Atom project will not flicker anymore since the default installation of both racer + atom gives unwanted behaviour (Hide Ignore Names is not checked by default). Something that every user needs to fix over and over again.
