### ISSUE TITLE
Racer isnt working

### ISSUE THREAD

**Issue by dariusc93** [edubkendo/atom-racer#34]
After several attempts, I couldnt get atom-racer working with atom. I reinstalled it, relocated racer and rust source but there is no completion, nor any sign of it being operational. Any clue as to why?

**Comment by alkama** [comment]
Hello darius!
Can you post your config (the racer section) here?

**Comment by dariusc93** [comment]
I am using Linux (both Ubuntu and Arch Linux)

```
  racer:
    rustSrcPath: "/home/darius/Projects/Software/rust/src"
    racerBinPath: "/home/darius/Projects/Other/racer/target/release/racer"
```

**Comment by alkama** [comment]
Hum, there is nothing obviously wrong there.

Can you check that racer does its job by hand?
You can follow instructions there: https://github.com/edubkendo/atom-racer/pull/29#issuecomment-110484861

This would ensure that the problem is on our package's hands.

You can also inspect for errors in the developer tools (menu `View -> Developer -> Toggle Developer Tools` and report of you see errors from us there :)

Happy hunting!

**Comment by dariusc93** [comment]
Yes racer runs fine by cli and there havent been any errors in the developer tools and the instructions there works fine. I would clear out atom and every package to be sure too.

**Comment by alkama** [comment]
Hum... is the core package "autocomplete-plus" active and running?

**Comment by dariusc93** [comment]
So far yes because the go plus works and if i recall, it requires autocomplete-plus.

**Comment by alkama** [comment]
Well, the last thing is to check that your project's directory is writable.
But I guess if it wasn't you would have errors in the developer tools. So i'm out of ideas.
Maybe you can troubleshoot it yourself by opening our package sources and putting logs to see where it fails?

**Comment by dariusc93** [comment]
I will dig around and see. I did reset atom back to its default state with racer being the only thing I installed into it. Is there any additional steps that must be taken for this after installing racer and configuring the path? I do see people have this working without problems, I just find it odd about why it would not work for me (its enabled but its as if its not enabled because there is no sign, error, or anything of it being operational even while using something simple as `use std::`).

**Comment by alkama** [comment]
Yeah, that's quite puzzling. It should indeed work without problem, or at least complain in the logs. That's why I'm pretty clueless.
And there's nothing that really needs hard check, the plugin is pretty simple only uses 2 node dependencies and relies on autocomplete-plus.

But I'm pretty sure you'll find where it's stuck by putting logs. It's not a big packages, just 3 short files :)

**Comment by dariusc93** [comment]
True, it is a small file, but something is weird. There is no logging being done. I removed the paths from the configuration, and reloaded the package to see if it does log anything within the developers console, however there is nothing going on as if its not loaded or enabled, even though it is according to atom. I did modify the code itself and it is loaded base off the minor changes, but I guess I should log it differently

**Comment by alkama** [comment]
try to add `console.log("was hereX")` starting from the activation method in `lib/racer.coffee`, then follow into `racer-provider.coffee` then the `racer-client.coffee` ?

**Comment by alkama** [comment]
Remember that after each source-code change in packages, you have to reload the whole Atom for the change to be taken into account.
There is a command called `Window:reload` that you can trigger with the usual palette.

**Comment by alkama** [comment]
Oh, btw, did you load "langage-rust" package? Maybe we overlooked that. Our plugin only work on `.source.rust` scopes, and I dont remember if that scope is default in Atom or if it's added by the language package. Anyway, we only activate on rust code, so .rs files or files that have synthax changed to rust.

**Comment by dariusc93** [comment]
I havent loaded `language-rust` but after installing it, everything does started to work and everything did started to log as well. I was editing the .rs files before installing and it was a no go until afterwards.

**Comment by edubkendo** [comment]
good call @alkama . Yeah, we should add that to the README probably, it's definitely a requirement/dependency

**Comment by edubkendo** [comment]
we could add a warning to print to the console to, for future hair-pulling events like this one

**Comment by alkama** [comment]
I updated the readme instead.
In fact, to be activated properly by autocomplete-plus as a provider for rust sources, we have to submit a scope. We use the `.source.rust` scope and that scope is declared and defined by the `language-rust` package.
I'm a tad reluctant to add code just to check that this package is present and log errors when it's not since we dont really do anything ourselves with that package.
Maybe when we'll have proper dialogs easy to display to users.
For now, console logs are so silent that it's not really useful.
