### ISSUE TITLE
A symlink at /usr/local/bin/racer that points to wherever your racer binary is does not work.

### ISSUE THREAD

**Issue by nelsonjchen** [edubkendo/atom-racer#40]
Hmm, I was wondering why everything appeared to work from the command line but not in Atom. I was also wondering why I remember it working before whatever I was doing now. Apparently, I had copied the binary, not a symlink in this newer installation I've done.

Anyway, a symlink at `/usr/local/bin/racer` that points to wherever the `racer` binary may be placed after compilation doesn't appear to work. My coffeescript skills are non-existent but I bet it has something to do with [this](https://github.com/edubkendo/atom-racer/blob/08c50bda0f4654c789473d7a68292cf8856915d4/lib/racer-client.coffee#L73).

**Comment by alkama** [comment]
Hello @nelsonjchen,
Indeed we didn't assume the path provided would link to a symbolic one.

The change is in fact to be done the line [above the one you cite](https://github.com/edubkendo/atom-racer/blob/08c50bda0f4654c789473d7a68292cf8856915d4/lib/racer-client.coffee#L72)
the
```coffee
stats = fs.lstatSync(conf_bin);
```
should become:
```coffee
stats = fs.statSync(conf_bin);
```
to stat the file that the symlink refers to instead of stat-ing the link itself.

I'll correct this tonight.

**Comment by nelsonjchen** [comment]
Great! Thank you.
